std = "lua51"
max_line_length = false
exclude_files = {
	"**/Libs",
}
ignore = {
	"212", -- Unused argument
}
globals = {
	"LibStub",
	"HuokanPayout",
	"GetCoinTextureString",
	"strsplit",
	"COPPER_PER_GOLD",
	"COPPER_PER_SILVER",
	"CreateFrame",
	"SendMail",
	"SetSendMailMoney",
	"C_Timer",
	"GetMoney",
	"UnitIsUnit",
	"MailFrame",
	"date",
	"GetServerTime",
	"C_Mail",
	"hooksecurefunc",
	"GetInboxHeaderInfo",
	"TakeInboxMoney",
	"GetInboxNumItems",
	"InboxFrame",
	"MailItem1",
	"PostalSelectOpenButton",
	"InboxNextPageButton",
	"InboxPrevPageButton",
	"GetInboxText",
	"GetRealmName",
	"InterfaceOptionsFrame_OpenToCategory",
	"GetSendMailPrice",
	"GetTime",
	"UnitName",
	"GetNormalizedRealmName",
	"bit",
	"GetGuildInfo",
	"IsInGuild",
	"C_Club",
	"TradeFrame",
	"ChatFontNormal",
	"TradeFrameTradeButton",
	"GetTradePlayerItemInfo",
	"GetTradeTargetItemInfo",
}
